// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4AGJmPogZiJjKyiB1Y_h-wLj8zmffvU',
    appId: '1:339156829686:web:21dd01c44c90516522f3d7',
    messagingSenderId: '339156829686',
    projectId: 'heritagebookapp-8f680',
    authDomain: 'heritagebookapp-8f680.firebaseapp.com',
    storageBucket: 'heritagebookapp-8f680.appspot.com',
    measurementId: 'G-KJQVCCLDGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0M1767TnYmLsL_bjtq4mp4vT6C2z7Zxg',
    appId: '1:339156829686:android:4577bfb21085d1c922f3d7',
    messagingSenderId: '339156829686',
    projectId: 'heritagebookapp-8f680',
    storageBucket: 'heritagebookapp-8f680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKdUc2Ha-fNulRn_9s9gGBQaGHpearxjw',
    appId: '1:339156829686:ios:1529628168c3efcd22f3d7',
    messagingSenderId: '339156829686',
    projectId: 'heritagebookapp-8f680',
    storageBucket: 'heritagebookapp-8f680.appspot.com',
    iosBundleId: 'com.example.heritage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKdUc2Ha-fNulRn_9s9gGBQaGHpearxjw',
    appId: '1:339156829686:ios:39c470ac09c0ba5422f3d7',
    messagingSenderId: '339156829686',
    projectId: 'heritagebookapp-8f680',
    storageBucket: 'heritagebookapp-8f680.appspot.com',
    iosBundleId: 'com.example.heritage.RunnerTests',
  );
}
